'use client';

/**
 * Content Generation Modal
 *
 * x402-payment-gated image generation via POST /api/services/image-generate[-pro].
 * All images are generated by nanobanana 2 and paid in USDC on-chain.
 */

import { useState, useRef } from 'react';
import Image from 'next/image';
import { useQueryClient } from '@tanstack/react-query';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card } from '@/components/ui/card';
import {
  Loader2,
  Check,
  AlertCircle,
  Share2,
  RefreshCw,
  Library,
  Coins,
} from 'lucide-react';
import { useX402Generate } from '@/hooks/use-x402-generate';
import { cn } from '@/lib/utils';
import type { X402GenerateType } from '@/hooks/use-x402-generate';
import { PublishModal } from './publish-modal';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface GenerateModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  characterId: string;
  characterName: string;
}

// ---------------------------------------------------------------------------
// Model config
// ---------------------------------------------------------------------------

const MODELS: { type: X402GenerateType; name: string; description: string; price: string }[] = [
  {
    type: 'image',
    name: 'nanobanana 2',
    description: 'Fast, high-quality image generation',
    price: '$0.10 USDC',
  },
  {
    type: 'image-pro',
    name: 'nanobanana 2 Pro',
    description: 'High-resolution, premium output',
    price: '$0.15 USDC',
  },
];

// ---------------------------------------------------------------------------
// Payment confirmation overlay
// ---------------------------------------------------------------------------

interface PaymentConfirmProps {
  amountUsdc: string;
  payTo: string;
  onConfirm: () => void;
  onCancel: () => void;
}

function PaymentConfirmOverlay({ amountUsdc, payTo, onConfirm, onCancel }: PaymentConfirmProps) {
  const shortAddress = `${payTo.slice(0, 6)}...${payTo.slice(-4)}`;

  return (
    <Card className="border-[#10B981]/30 bg-[#10B981]/5 p-6">
      <div className="space-y-4">
        <div className="flex items-start gap-3">
          <Coins className="mt-0.5 h-5 w-5 shrink-0 text-[#10B981]" />
          <div className="flex-1 space-y-1">
            <p className="font-medium text-foreground">Confirm USDC Payment</p>
            <p className="text-sm text-muted-foreground">
              Your wallet will be prompted to sign a USDC transfer. No SOL is spent beyond
              the transaction fee.
            </p>
          </div>
        </div>

        <div className="space-y-2 rounded-lg border border-border bg-[#18181B] p-4 text-sm">
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Amount</span>
            <span className="font-medium text-[#10B981]">{amountUsdc} USDC</span>
          </div>
          <div className="flex items-center justify-between">
            <span className="text-muted-foreground">Recipient</span>
            <span className="font-mono text-xs text-foreground">{shortAddress}</span>
          </div>
        </div>

        <div className="flex gap-2">
          <Button variant="outline" size="sm" className="flex-1" onClick={onCancel}>
            Cancel
          </Button>
          <Button
            size="sm"
            className="flex-1 bg-[#10B981] text-black hover:bg-[#10B981]/90"
            onClick={onConfirm}
          >
            <Check className="mr-2 h-4 w-4" />
            Confirm &amp; Sign
          </Button>
        </div>
      </div>
    </Card>
  );
}

// ---------------------------------------------------------------------------
// Main modal
// ---------------------------------------------------------------------------

export function GenerateModal({
  open,
  onOpenChange,
  characterId,
  characterName,
}: GenerateModalProps) {
  const [prompt, setPrompt] = useState('');
  const [modelType, setModelType] = useState<X402GenerateType>('image');
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [genError, setGenError] = useState<string | null>(null);
  const [publishOpen, setPublishOpen] = useState(false);

  const [pendingConfirmation, setPendingConfirmation] = useState<{
    amountUsdc: string;
    payTo: string;
  } | null>(null);

  const confirmResolverRef = useRef<(() => void) | null>(null);
  const confirmRejecterRef = useRef<((reason?: unknown) => void) | null>(null);

  const queryClient = useQueryClient();

  const { mutate: generate, isPending, reset } = useX402Generate({
    onConfirm: async ({ amountUsdc, payTo }) => {
      return new Promise<void>((resolve, reject) => {
        confirmResolverRef.current = resolve;
        confirmRejecterRef.current = reject;
        setPendingConfirmation({ amountUsdc, payTo });
      });
    },
  });

  // -------------------------------------------------------------------------
  // Derived flags
  // -------------------------------------------------------------------------
  const isGenerating = isPending && !pendingConfirmation;
  const hasResult = !!imageUrl;

  // -------------------------------------------------------------------------
  // Handlers
  // -------------------------------------------------------------------------
  const handleSubmit = () => {
    if (!prompt.trim()) return;
    setImageUrl(null);
    setGenError(null);

    generate(
      { characterId, prompt: prompt.trim(), type: modelType },
      {
        onSuccess: (result) => {
          setImageUrl(result.imageUrl);
          void queryClient.invalidateQueries({ queryKey: ['character-generations', characterId] });
        },
        onError: (err) => {
          setGenError(err instanceof Error ? err.message : 'Generation failed');
        },
      }
    );
  };

  const handleGenerateAgain = () => {
    setImageUrl(null);
    setGenError(null);
    setPrompt('');
    reset();
  };

  const handleConfirmPayment = () => {
    setPendingConfirmation(null);
    confirmResolverRef.current?.();
    confirmResolverRef.current = null;
    confirmRejecterRef.current = null;
  };

  const handleCancelPayment = () => {
    setPendingConfirmation(null);
    confirmRejecterRef.current?.(new Error('User cancelled payment'));
    confirmResolverRef.current = null;
    confirmRejecterRef.current = null;
    setGenError('Payment cancelled');
    reset();
  };

  const handleClose = () => {
    onOpenChange(false);
    setTimeout(() => {
      setPrompt('');
      setImageUrl(null);
      setGenError(null);
      setPendingConfirmation(null);
      confirmRejecterRef.current?.(new Error('Modal closed'));
      confirmResolverRef.current = null;
      confirmRejecterRef.current = null;
      reset();
    }, 300);
  };

  const selectedModel = MODELS.find((m) => m.type === modelType) ?? MODELS[0];

  // -------------------------------------------------------------------------
  // Render
  // -------------------------------------------------------------------------
  return (
    <>
      <Dialog open={open} onOpenChange={handleClose}>
        <DialogContent className="max-h-[90vh] max-w-2xl overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Generate Image</DialogTitle>
            <DialogDescription>Create an image with {characterName}</DialogDescription>
          </DialogHeader>

          {/* ================================================================
              Form — hidden while pending / showing result
              ================================================================ */}
          {!hasResult && !isGenerating && !pendingConfirmation && !genError && (
            <div className="space-y-5">
              {/* Model selector */}
              <div className="space-y-2">
                <Label>Model</Label>
                <div className="grid grid-cols-2 gap-2">
                  {MODELS.map((m) => (
                    <button
                      key={m.type}
                      type="button"
                      onClick={() => setModelType(m.type)}
                      className={cn(
                        'rounded-lg border p-3 text-left transition-colors',
                        modelType === m.type
                          ? 'border-[#10B981]/60 bg-[#10B981]/10'
                          : 'border-[#27272A] bg-[#18181B] hover:border-[#10B981]/30'
                      )}
                    >
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-semibold">{m.name}</span>
                        {modelType === m.type && <Check className="h-4 w-4 text-[#10B981]" />}
                      </div>
                      <p className="mt-0.5 text-xs text-muted-foreground">{m.description}</p>
                      <p className="mt-1 text-xs font-semibold text-[#10B981]">{m.price}</p>
                    </button>
                  ))}
                </div>
              </div>

              {/* Prompt */}
              <div className="space-y-2">
                <Label htmlFor="prompt">Prompt</Label>
                <Textarea
                  id="prompt"
                  placeholder="Paint a picture. What should the world see?"
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  rows={6}
                  maxLength={2000}
                />
                <p className="text-xs text-muted-foreground">{prompt.length}/2000 characters</p>
              </div>

              {/* Cost summary */}
              <div className="flex items-center justify-between rounded-lg border border-[#27272A] bg-[#18181B] px-4 py-2 text-sm">
                <span className="text-muted-foreground">Cost</span>
                <span className="font-semibold text-[#10B981]">{selectedModel.price}</span>
              </div>

              <Button
                onClick={handleSubmit}
                disabled={!prompt.trim() || isPending}
                className="w-full bg-[#10B981] font-semibold text-black hover:bg-[#10B981]/90"
              >
                <Coins className="mr-2 h-4 w-4" />
                Generate &amp; Pay {selectedModel.price}
              </Button>

              <p className="text-center text-xs text-muted-foreground">
                Payment is processed on-chain via your connected wallet. No funds are held by
                ozskr.ai.
              </p>
            </div>
          )}

          {/* ================================================================
              Payment confirmation overlay
              ================================================================ */}
          {pendingConfirmation && (
            <PaymentConfirmOverlay
              amountUsdc={pendingConfirmation.amountUsdc}
              payTo={pendingConfirmation.payTo}
              onConfirm={handleConfirmPayment}
              onCancel={handleCancelPayment}
            />
          )}

          {/* ================================================================
              Generating spinner
              ================================================================ */}
          {isGenerating && (
            <Card className="border-[#10B981]/20 bg-[#10B981]/5 p-6">
              <div className="flex flex-col items-center gap-3 py-4" aria-live="polite">
                <Loader2 className="h-8 w-8 animate-spin text-[#10B981]" />
                <p className="text-sm font-medium">Generating with {selectedModel.name}...</p>
                <p className="text-xs text-muted-foreground">Submitting payment and running model</p>
              </div>
            </Card>
          )}

          {/* ================================================================
              Error state
              ================================================================ */}
          {genError && !isPending && (
            <div className="space-y-4">
              <Card className="border-destructive/50 bg-destructive/10 p-6">
                <div className="flex items-start gap-3">
                  <AlertCircle className="h-5 w-5 text-destructive" />
                  <div className="flex-1">
                    <h3 className="font-medium text-destructive">Generation Failed</h3>
                    <p className="mt-1 text-sm text-destructive/80">{genError}</p>
                  </div>
                </div>
              </Card>
              <Button onClick={handleGenerateAgain} variant="outline" className="w-full">
                <RefreshCw className="mr-2 h-4 w-4" />
                Try Again
              </Button>
            </div>
          )}

          {/* ================================================================
              Result display
              ================================================================ */}
          {hasResult && imageUrl && (
            <div className="space-y-4">
              <div className="flex items-center gap-2 rounded-lg border border-[#10B981]/20 bg-[#10B981]/5 px-4 py-3">
                <Check className="h-4 w-4 shrink-0 text-[#10B981]" />
                <p className="text-sm font-medium text-[#10B981]">
                  Image generated and paid via USDC
                </p>
              </div>

              <div className="relative w-full overflow-hidden rounded-xl">
                <Image
                  src={imageUrl}
                  alt="Generated image"
                  width={600}
                  height={600}
                  className="w-full object-contain"
                  priority
                />
              </div>

              <div className="flex gap-2">
                <Button onClick={handleGenerateAgain} variant="outline" className="flex-1">
                  <RefreshCw className="mr-2 h-4 w-4" />
                  Create More
                </Button>
                <Button
                  className="flex-1 bg-gradient-to-r from-solana-purple to-solana-green hover:opacity-90"
                  onClick={() => setPublishOpen(true)}
                >
                  <Share2 className="mr-2 h-4 w-4" />
                  Publish
                </Button>
              </div>
              <Button
                variant="ghost"
                size="sm"
                className="w-full gap-2 text-muted-foreground hover:text-foreground"
                onClick={handleClose}
              >
                <Library className="h-4 w-4" />
                View in Library
              </Button>
            </div>
          )}
        </DialogContent>
      </Dialog>

      {hasResult && (
        <PublishModal
          open={publishOpen}
          onOpenChange={setPublishOpen}
          contentGenerationId="premium"
          outputText={null}
          outputUrl={imageUrl}
        />
      )}
    </>
  );
}
