name: Feature Request
description: Suggest a new feature for ozskr.ai
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the desired behavior or implementation approach.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches or workarounds you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      options:
        - AI Agents / Content Pipeline
        - Trading / DeFi
        - Social Publishing
        - Dashboard / UI
        - Analytics
        - Gamification
        - Infrastructure
        - Other
    validations:
      required: true
