/**
 * AI Content Disclosure
 * Automatically injects AI-generated content disclosure into social posts.
 *
 * Compliance targets:
 * - NY S.B. S6524-A: AI-generated content must be labeled
 * - FTC 16 CFR §255: Endorsement disclosures
 * - Platform TOS: Twitter/X, Instagram AI content policies
 */

import { logger } from '@/lib/utils/logger';

/**
 * Default AI disclosure tag appended to all published content
 */
const AI_DISCLOSURE_TAG = '#AIGenerated';

/**
 * Character limit for Twitter/X posts
 */
const TWITTER_CHAR_LIMIT = 280;

/**
 * Check if content already contains an AI disclosure
 */
export const hasAiDisclosure = (text: string): boolean => {
  const lowerText = text.toLowerCase();
  return (
    lowerText.includes('#aigenerated') ||
    lowerText.includes('#aigenerated') ||
    lowerText.includes('#ai-generated') ||
    lowerText.includes('ai-generated') ||
    lowerText.includes('generated by ai') ||
    lowerText.includes('created by ai') ||
    lowerText.includes('made with ai') ||
    lowerText.includes('#madewith ai') ||
    lowerText.includes('#madewithai')
  );
};

/**
 * Inject AI disclosure into post text if not already present.
 *
 * For Twitter (280 char limit), ensures the disclosure fits.
 * If the post is too long with disclosure, it truncates the post
 * text to make room — the disclosure is NEVER dropped.
 *
 * @param text - Original post text
 * @param charLimit - Optional character limit (default: no limit)
 * @returns Text with AI disclosure injected
 */
export const injectAiDisclosure = (
  text: string,
  charLimit?: number
): string => {
  // Skip if disclosure already present
  if (hasAiDisclosure(text)) {
    return text;
  }

  const disclosure = ` ${AI_DISCLOSURE_TAG}`;

  // If no character limit or fits within limit, just append
  if (!charLimit || text.length + disclosure.length <= charLimit) {
    return `${text}${disclosure}`;
  }

  // Truncate text to fit disclosure within character limit
  const maxTextLength = charLimit - disclosure.length - 1; // -1 for ellipsis
  const truncatedText = text.slice(0, maxTextLength) + '\u2026';

  logger.warn('Post text truncated to fit AI disclosure', {
    originalLength: text.length,
    truncatedLength: truncatedText.length,
    charLimit,
  });

  return `${truncatedText}${disclosure}`;
};

/**
 * Inject AI disclosure for Twitter posts (280 char limit)
 */
export const injectTwitterAiDisclosure = (text: string): string => {
  return injectAiDisclosure(text, TWITTER_CHAR_LIMIT);
};
