/**
 * AI Disclosure Tests
 * Tests for auto-injection of AI-generated content disclosure
 */

import { describe, it, expect, vi } from 'vitest';
import { hasAiDisclosure, injectAiDisclosure, injectTwitterAiDisclosure } from './ai-disclosure';

vi.mock('@/lib/utils/logger', () => ({
  logger: {
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  },
}));

describe('hasAiDisclosure', () => {
  it('detects #AIGenerated tag', () => {
    expect(hasAiDisclosure('Hello world #AIGenerated')).toBe(true);
  });

  it('detects case-insensitive #aigenerated', () => {
    expect(hasAiDisclosure('Hello world #aigenerated')).toBe(true);
  });

  it('detects "generated by ai"', () => {
    expect(hasAiDisclosure('This was generated by AI.')).toBe(true);
  });

  it('detects "created by ai"', () => {
    expect(hasAiDisclosure('Content created by AI for you')).toBe(true);
  });

  it('detects "made with ai"', () => {
    expect(hasAiDisclosure('Made with AI tools')).toBe(true);
  });

  it('detects #MadeWithAI hashtag', () => {
    expect(hasAiDisclosure('Check this out #MadeWithAI')).toBe(true);
  });

  it('returns false when no disclosure present', () => {
    expect(hasAiDisclosure('Just a normal tweet about Solana')).toBe(false);
  });

  it('returns false for empty string', () => {
    expect(hasAiDisclosure('')).toBe(false);
  });
});

describe('injectAiDisclosure', () => {
  it('appends #AIGenerated to text without disclosure', () => {
    const result = injectAiDisclosure('Hello world');
    expect(result).toBe('Hello world #AIGenerated');
  });

  it('does not double-inject if disclosure already present', () => {
    const text = 'Hello world #AIGenerated';
    const result = injectAiDisclosure(text);
    expect(result).toBe(text);
  });

  it('does not double-inject for case variations', () => {
    const text = 'Hello world #aigenerated';
    const result = injectAiDisclosure(text);
    expect(result).toBe(text);
  });

  it('skips injection for "made with ai" text', () => {
    const text = 'This was made with AI';
    const result = injectAiDisclosure(text);
    expect(result).toBe(text);
  });

  it('respects character limit by truncating text', () => {
    const longText = 'A'.repeat(275);
    const result = injectAiDisclosure(longText, 280);
    expect(result.length).toBeLessThanOrEqual(280);
    expect(result).toContain('#AIGenerated');
  });

  it('does not truncate when text + disclosure fits within limit', () => {
    const text = 'Short tweet';
    const result = injectAiDisclosure(text, 280);
    expect(result).toBe('Short tweet #AIGenerated');
  });

  it('handles no character limit', () => {
    const longText = 'A'.repeat(1000);
    const result = injectAiDisclosure(longText);
    expect(result).toBe(longText + ' #AIGenerated');
  });
});

describe('injectTwitterAiDisclosure', () => {
  it('injects disclosure for normal tweets', () => {
    const result = injectTwitterAiDisclosure('Building on Solana');
    expect(result).toBe('Building on Solana #AIGenerated');
  });

  it('enforces 280 character limit', () => {
    const longTweet = 'A'.repeat(275);
    const result = injectTwitterAiDisclosure(longTweet);
    expect(result.length).toBeLessThanOrEqual(280);
    expect(result).toContain('#AIGenerated');
  });

  it('preserves existing disclosure without modification', () => {
    const tweet = 'AI agents are cool #AIGenerated';
    const result = injectTwitterAiDisclosure(tweet);
    expect(result).toBe(tweet);
  });
});
