-- content_calendar: per-slot calendar entries generated by contentCalendarCreate tool
-- Separate from content_schedules (which stores recurring schedule configs)
create table if not exists public.content_calendar (
  id uuid primary key default gen_random_uuid(),
  character_id uuid not null references public.characters(id) on delete cascade,
  wallet_address text not null,
  scheduled_at timestamptz not null,
  platform text not null check (platform in ('twitter', 'instagram', 'linkedin', 'tiktok')),
  content_brief text not null,           -- 1-2 sentence idea from contentCalendarCreate
  content_text text,                     -- full generated content (if generated)
  content_type text not null default 'text' check (content_type in ('text', 'image', 'video')),
  status text not null default 'draft' check (status in ('draft', 'scheduled', 'published', 'failed')),
  trigger_schedule_id text,              -- Trigger.dev task run ID for tracking
  error_message text,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- RLS
alter table public.content_calendar enable row level security;

create policy "Users can view their own calendar entries"
  on public.content_calendar for select
  using (wallet_address = auth.jwt()->>'wallet_address');

create policy "Users can insert their own calendar entries"
  on public.content_calendar for insert
  with check (wallet_address = auth.jwt()->>'wallet_address');

create policy "Users can update their own calendar entries"
  on public.content_calendar for update
  using (wallet_address = auth.jwt()->>'wallet_address');

create policy "Users can delete their own calendar entries"
  on public.content_calendar for delete
  using (wallet_address = auth.jwt()->>'wallet_address');

-- Indexes
create index content_calendar_character_id_idx on public.content_calendar(character_id);
create index content_calendar_scheduled_at_idx on public.content_calendar(scheduled_at);
create index content_calendar_status_idx on public.content_calendar(status);
create index content_calendar_wallet_address_idx on public.content_calendar(wallet_address);

-- updated_at trigger
create trigger update_content_calendar_updated_at
  before update on public.content_calendar
  for each row execute procedure public.update_updated_at_column();
